resources:
- ../base/
patchesStrategicMerge:
- |-
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: frontend
      labels:
        app.kubernetes.io/name: guestbook
        app.kubernetes.io/component: frontend
    spec:
      selector:
        matchLabels:
          app.kubernetes.io/name: guestbook
          app.kubernetes.io/component: frontend
      replicas: 2
      template:
        metadata:
          labels:
            app.kubernetes.io/name: guestbook
            app.kubernetes.io/component: frontend
            test: test
        spec:
          containers:
          - name: guestbook
            resources:
              requests:
                cpu: 20m
                memory: 20Mi
              limits:
                cpu: 520m
                memory: 520Mi
